### ISSUE TITLE
[HU] Como programador necesito necesito conocer como se manejan los errores en el lenguaje de mi proyecto

### ISSUE THREAD

**Issue by Kevincamp** [Golang-EC/go-notes#23]
## Descripción de alto nivel

*Como un **programador** necesito una **definir al menos una excepcion** para poder hacer **entender el manejo de las excepciones en el lenguaje de mi proyecto** *

## Dado/Y/Entonces/Cuando
Dado que el proyecto esta hecho en Go
Entonces debo de conocer como se aplican las excepciones en él para tratar
Cuando salte una excepción en algún escenario

**Comment by rpalaciosg** [comment]
Este issue se lo debe cerrar, al hacer un commit poner close #issue en el mensaje voy a intentar y enviar este cambio en el fork del PR que haces a curso-tdd.
