### ISSUE TITLE
[HU]  Como Profesor necesito publicar las notas de los alumnos en la asignatura que enseño

### ISSUE THREAD

**Issue by gomezgleonardob** [Golang-EC/go-notes#6]
## Descripción de alto nivel

*Como un **profesor** necesito  publicar  la  **nota** que obtuvo cada  alumno en mi **asignatura** *

## Dado/Y/Entonces/Cuando

Como profesor debo **publicar** la **nota** cuando haya calificado
las tareas que me entregan los **alumnos**

**Comment by rpalaciosg** [comment]
🐱‍💻
