### ISSUE TITLE
Como profe, quiero ver que la versión "major" corresponda con el hito

### ISSUE THREAD

**Issue by JJ** [Golang-EC/go-notes#9]
## Descripción de alto nivel

*Como un profesor necesito que la versión *major* corresponda con el hito para poder hacer **los tests correctos** *

## Dado/Y/Entonces/Cuando

Dado que estáis usando el númeor de versión en la "point" (última), deberíais volver a enviarlo poniendo el número de versión del hito en la primera posición. Por ejemplo, el hito 3 → 3.x.y

**Comment by Kevincamp** [comment]
Atentos @rpalaciosg @gomezgleonardob  para los siguientes hitos hacerlos con el release correspondientes

Gracias @JJ lo tomamos

**Comment by rpalaciosg** [comment]
Listo @Kevincamp  y muchas gracias @JJ ahora lo enviamos.
